/**
 * All 18 creature species definitions.
 * Matches spec section 5.2 exactly.
 */
export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export type ScheduleType = 'diurnal' | 'nocturnal' | 'crepuscular';
export type CreatureType = 'herbivore' | 'carnivore' | 'aquatic';

export interface SpeciesDef {
  id: string;
  name: string;
  type: CreatureType;
  schedule: ScheduleType;
  /** Minimum terrain % or special count conditions for wild spawn */
  terrain: Record<string, number>;
  rarity: Rarity;
  dropWeight: number;
  shinyRate: number;
  resourceId: string;
  productionInterval: number; // seconds
  sellPrice: number;
  /** Visual accent color for sprite rendering */
  primaryColor: string;
  secondaryColor: string;
}

export const SPECIES: readonly SpeciesDef[] = [
  // ── HERBIVORES ──────────────────────────────────────────────────────────
  {
    id: 'feuillon',
    name: 'Feuillon',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { grass: 30 },
    rarity: 'common',
    dropWeight: 40,
    shinyRate: 0.02,
    resourceId: 'seeds',
    productionInterval: 3600,
    sellPrice: 50,
    primaryColor: '#8AC659',
    secondaryColor: '#5AA832',
  },
  {
    id: 'broutard',
    name: 'Broutard',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { grass: 50 },
    rarity: 'common',
    dropWeight: 35,
    shinyRate: 0.02,
    resourceId: 'wicker',
    productionInterval: 7200,
    sellPrice: 50,
    primaryColor: '#C8956A',
    secondaryColor: '#A07040',
  },
  {
    id: 'boussin',
    name: 'Boussin',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { flowers: 20 },
    rarity: 'common',
    dropWeight: 30,
    shinyRate: 0.03,
    resourceId: 'pollen',
    productionInterval: 3600,
    sellPrice: 50,
    primaryColor: '#F9A8D4',
    secondaryColor: '#EC4899',
  },
  {
    id: 'mellior',
    name: 'Mellior',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { flowers: 30 },
    rarity: 'uncommon',
    dropWeight: 20,
    shinyRate: 0.02,
    resourceId: 'honey',
    productionInterval: 10800,
    sellPrice: 150,
    primaryColor: '#FCD34D',
    secondaryColor: '#F59E0B',
  },
  {
    id: 'rampex',
    name: 'Rampex',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { forest: 30 },
    rarity: 'uncommon',
    dropWeight: 18,
    shinyRate: 0.02,
    resourceId: 'wood',
    productionInterval: 7200,
    sellPrice: 150,
    primaryColor: '#8B5E3C',
    secondaryColor: '#5C3A1E',
  },
  {
    id: 'gribou',
    name: 'Gribou',
    type: 'herbivore',
    schedule: 'crepuscular',
    terrain: { forest: 40 },
    rarity: 'uncommon',
    dropWeight: 15,
    shinyRate: 0.02,
    resourceId: 'mushrooms',
    productionInterval: 10800,
    sellPrice: 150,
    primaryColor: '#7C3AED',
    secondaryColor: '#5B21B6',
  },
  {
    id: 'crochon',
    name: 'Crochon',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: { rock: 40 },
    rarity: 'uncommon',
    dropWeight: 14,
    shinyRate: 0.02,
    resourceId: 'ore',
    productionInterval: 14400,
    sellPrice: 150,
    primaryColor: '#8A9A7A',
    secondaryColor: '#6A7A5A',
  },
  {
    id: 'stalagor',
    name: 'Stalagor',
    type: 'herbivore',
    schedule: 'nocturnal',
    terrain: { rock: 60 },
    rarity: 'rare',
    dropWeight: 8,
    shinyRate: 0.04,
    resourceId: 'crystals',
    productionInterval: 21600,
    sellPrice: 400,
    primaryColor: '#1E3A5F',
    secondaryColor: '#2563EB',
  },
  // ── CARNIVORES ───────────────────────────────────────────────────────────
  {
    id: 'scorpilou',
    name: 'Scorpilou',
    type: 'carnivore',
    schedule: 'nocturnal',
    terrain: { sand: 30 },
    rarity: 'uncommon',
    dropWeight: 12,
    shinyRate: 0.03,
    resourceId: 'venom',
    productionInterval: 21600,
    sellPrice: 150,
    primaryColor: '#F97316',
    secondaryColor: '#EA580C',
  },
  {
    id: 'dunor',
    name: 'Dunor',
    type: 'carnivore',
    schedule: 'nocturnal',
    terrain: { sand: 50 },
    rarity: 'rare',
    dropWeight: 7,
    shinyRate: 0.04,
    resourceId: 'goldSand',
    productionInterval: 28800,
    sellPrice: 400,
    primaryColor: '#D97706',
    secondaryColor: '#92400E',
  },
  {
    id: 'griffax',
    name: 'Griffax',
    type: 'carnivore',
    schedule: 'diurnal',
    terrain: { herbivoreCount: 5 },
    rarity: 'uncommon',
    dropWeight: 10,
    shinyRate: 0.03,
    resourceId: 'feathers',
    productionInterval: 21600,
    sellPrice: 150,
    primaryColor: '#374151',
    secondaryColor: '#6B7280',
  },
  {
    id: 'rughor',
    name: 'Rughor',
    type: 'carnivore',
    schedule: 'diurnal',
    terrain: { herbivoreCount: 8 },
    rarity: 'rare',
    dropWeight: 6,
    shinyRate: 0.04,
    resourceId: 'fur',
    productionInterval: 28800,
    sellPrice: 400,
    primaryColor: '#92400E',
    secondaryColor: '#78350F',
  },
  {
    id: 'venomoth',
    name: 'Vénomoth',
    type: 'carnivore',
    schedule: 'nocturnal',
    terrain: { scorpilouCount: 3 },
    rarity: 'rare',
    dropWeight: 4,
    shinyRate: 0.05,
    resourceId: 'rareToxin',
    productionInterval: 43200,
    sellPrice: 400,
    primaryColor: '#581C87',
    secondaryColor: '#7C3AED',
  },
  // ── AQUATICS ─────────────────────────────────────────────────────────────
  {
    id: 'flottin',
    name: 'Flottin',
    type: 'aquatic',
    schedule: 'diurnal',
    terrain: { water: 40 },
    rarity: 'common',
    dropWeight: 25,
    shinyRate: 0.02,
    resourceId: 'purifiedWater',
    productionInterval: 3600,
    sellPrice: 50,
    primaryColor: '#38BDF8',
    secondaryColor: '#0EA5E9',
  },
  {
    id: 'sirpio',
    name: 'Sirpio',
    type: 'aquatic',
    schedule: 'diurnal',
    terrain: { water: 60 },
    rarity: 'uncommon',
    dropWeight: 15,
    shinyRate: 0.03,
    resourceId: 'scales',
    productionInterval: 14400,
    sellPrice: 150,
    primaryColor: '#10B981',
    secondaryColor: '#059669',
  },
  // ── EPICS ────────────────────────────────────────────────────────────────
  {
    id: 'aquilon',
    name: 'Aquilon',
    type: 'aquatic',
    schedule: 'crepuscular',
    terrain: { water: 50, forest: 20 },
    rarity: 'epic',
    dropWeight: 2,
    shinyRate: 0.06,
    resourceId: 'pearl',
    productionInterval: 43200,
    sellPrice: 1000,
    primaryColor: '#0891B2',
    secondaryColor: '#0E7490',
  },
  {
    id: 'lumios',
    name: 'Lumios',
    type: 'herbivore',
    schedule: 'nocturnal',
    terrain: { flowers: 30, water: 20, nightOnly: 1 },
    rarity: 'epic',
    dropWeight: 1,
    shinyRate: 0.08,
    resourceId: 'lightEssence',
    productionInterval: 86400,
    sellPrice: 1000,
    primaryColor: '#FEFCE8',
    secondaryColor: '#FDE68A',
  },
  // ── LEGENDARY ────────────────────────────────────────────────────────────
  {
    id: 'draknoir',
    name: 'Draknoir',
    type: 'carnivore',
    schedule: 'nocturnal',
    terrain: { totalCreatures: 10, nightOnly: 1 },
    rarity: 'legendary',
    dropWeight: 0.2,
    shinyRate: 0.1,
    resourceId: 'darkSoul',
    productionInterval: 172800,
    sellPrice: 3000,
    primaryColor: '#1C1C2E',
    secondaryColor: '#6D28D9',
  },
  // ── HYBRIDS (Laboratory only — dropWeight 0, never spawn wild) ────────────
  {
    id: 'feulot',
    name: 'Feulot',
    type: 'aquatic',
    schedule: 'diurnal',
    terrain: {},
    rarity: 'rare',
    dropWeight: 0,
    shinyRate: 0.05,
    resourceId: 'dewPearl',
    productionInterval: 14400,
    sellPrice: 600,
    primaryColor: '#7EE8A2',
    secondaryColor: '#38BDF8',
  },
  {
    id: 'sylvax',
    name: 'Sylvax',
    type: 'carnivore',
    schedule: 'diurnal',
    terrain: {},
    rarity: 'rare',
    dropWeight: 0,
    shinyRate: 0.05,
    resourceId: 'raptorClaw',
    productionInterval: 21600,
    sellPrice: 600,
    primaryColor: '#4ADE80',
    secondaryColor: '#374151',
  },
  {
    id: 'terrak',
    name: 'Terrak',
    type: 'herbivore',
    schedule: 'diurnal',
    terrain: {},
    rarity: 'epic',
    dropWeight: 0,
    shinyRate: 0.07,
    resourceId: 'earthCrystal',
    productionInterval: 28800,
    sellPrice: 1200,
    primaryColor: '#A16207',
    secondaryColor: '#78350F',
  },
  {
    id: 'toxaris',
    name: 'Toxaris',
    type: 'carnivore',
    schedule: 'nocturnal',
    terrain: {},
    rarity: 'epic',
    dropWeight: 0,
    shinyRate: 0.07,
    resourceId: 'mutantPoison',
    productionInterval: 43200,
    sellPrice: 1200,
    primaryColor: '#7C3AED',
    secondaryColor: '#F97316',
  },
  {
    id: 'celestin',
    name: 'Célestin',
    type: 'aquatic',
    schedule: 'crepuscular',
    terrain: {},
    rarity: 'legendary',
    dropWeight: 0,
    shinyRate: 0.12,
    resourceId: 'starDust',
    productionInterval: 86400,
    sellPrice: 4000,
    primaryColor: '#E0F2FE',
    secondaryColor: '#FDE68A',
  },
] as const;

export const SPECIES_MAP = new Map(SPECIES.map((s) => [s.id, s]));

export const RARITY_COLOR: Record<string, string> = {
  common:    '#8DC99A',
  uncommon:  '#60A5FA',
  rare:      '#C084FC',
  epic:      '#F59E0B',
  legendary: '#EF4444',
};
